# Generated by Django 5.1.5 on 2025-02-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Утвержден'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='isu',
            field=models.CharField(max_length=6, verbose_name='Табельный номер (ИСУ)'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
