# Generated by Django 5.1.6 on 2025-03-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_serviceuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='github',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ник GitHub'),
        ),
    ]
