# Generated by Django 5.1.6 on 2025-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_serviceuser_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Github Username'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='github',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Github ID'),
        ),
    ]
