# Generated by Django 5.1.6 on 2025-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_serviceuser_github_username_alter_serviceuser_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Github Access Token'),
        ),
    ]
