services:
    django:
        build:
            context: ./back
            target: dev
            dockerfile: Dockerfile
        volumes:
            - "./back:/app"
        env_file:
            - .env
        networks:
            - pindb-network
    react:
        build:
            context: ./front
            dockerfile: Dockerfile
        volumes:
            - "./front:/app"
            - /app/node_modules
        networks:
            - pindb-network
        depends_on:
            - django
    nginx:
        image: nginx
        container_name: fpin-nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pindb-network
        restart: always
        depends_on:
            - react
            - django
        ports:
            - "80:80"
networks:
    pindb-network: