# Generated by Django 5.1.5 on 2025-01-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsentrance',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester'),
        ),
        migrations.AddField(
            model_name='flow',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.flow'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointsentrance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.student'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.flow'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.taskassignment'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.student'),
        ),
        migrations.AddField(
            model_name='pointsentrance',
            name='task_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.tasksubmission'),
        ),
        migrations.AddField(
            model_name='tasksubmissionstatus',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmissionstatus',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.tasksubmission'),
        ),
        migrations.AddField(
            model_name='tasksubmissionstatusattachment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.tasksubmissionstatus'),
        ),
    ]
