# Generated by Django 5.1.5 on 2025-02-04 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_student_is_approved_alter_tasksubmission_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'Поток', 'verbose_name_plural': 'Потоки'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='pointsentrance',
            options={'verbose_name': 'БАРС', 'verbose_name_plural': 'БАРС'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'verbose_name': 'Выдача задания', 'verbose_name_plural': 'Выдачи заданий'},
        ),
        migrations.AlterModelOptions(
            name='tasksubmission',
            options={'verbose_name': 'Сдача задания', 'verbose_name_plural': 'Сдачи заданий'},
        ),
        migrations.AlterModelOptions(
            name='tasksubmissionstatus',
            options={'verbose_name': 'Статус сдачи задания', 'verbose_name_plural': 'Статусы сдач заданий'},
        ),
        migrations.AlterModelOptions(
            name='tasksubmissionstatusattachment',
            options={'verbose_name': 'Вложение (сдача задания)', 'verbose_name_plural': 'Вложения (сдачи заданий)'},
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 8, 13, 7, 14093)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 8, 13, 7, 14370)),
        ),
    ]
