# Generated by Django 5.1.5 on 2025-02-04 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_tasksubmission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 12, 51, 37, 4727)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 12, 51, 37, 5057)),
        ),
        migrations.CreateModel(
            name='BarsStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('minimum_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('control_minimum', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester')),
            ],
        ),
        migrations.AddField(
            model_name='pointsentrance',
            name='bars_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.barsstates'),
        ),
    ]
