# Generated by Django 5.1.5 on 2025-02-04 10:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_rename_barsstates_barsstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='bars_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='education.barsstate'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 13, 5, 16, 43741)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 13, 5, 16, 44005)),
        ),
    ]
