# Generated by Django 5.1.5 on 2025-02-04 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_taskassignment_bars_state_alter_tasksubmission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='fine_per_week',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='fees_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 14, 8, 19, 24364)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 14, 8, 19, 24613)),
        ),
    ]
