# Generated by Django 5.1.5 on 2025-02-04 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_remove_taskassignment_fine_per_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmissionstatusattachment',
            old_name='attachment',
            new_name='url',
        ),
        migrations.AddField(
            model_name='tasksubmissionstatusattachment',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 15, 26, 33, 162934)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 15, 26, 33, 163245)),
        ),
    ]
