# Generated by Django 5.1.5 on 2025-02-05 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_rename_attachment_tasksubmissionstatusattachment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 11, 19, 11, 923253)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 11, 19, 11, 923524)),
        ),
    ]
