# Generated by Django 5.1.6 on 2025-03-01 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_alter_tasksubmission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 2, 7, 22, 627414)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 2, 7, 22, 628086)),
        ),
    ]
