# Generated by Django 5.1.6 on 2025-03-04 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_alter_tasksubmission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='chat_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 15, 20, 48, 200490)),
        ),
        migrations.AlterField(
            model_name='tasksubmissionstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 15, 20, 48, 201489)),
        ),
    ]
