# Generated by Django 5.1.6 on 2025-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_alter_tasksubmission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignments_block_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
