# Generated by Django 5.1.6 on 2025-03-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_tasksubmission_user'),
    ]

    operations = [
    ]
