# Generated by Django 5.1.11 on 2025-08-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0025_auto_20250317_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_obligatory', models.BooleanField()),
                ('type', models.CharField(choices=[('LECTURE', 'Лекция'), ('PRACTICE', 'Практика'), ('CONSULTATION', 'Консультация'), ('CREDIT', 'Зачет'), ('EXAM', 'Экзамен')], default='LECTURE', max_length=30)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='common_lessons',
            field=models.ManyToManyField(to='education.commonlesson'),
        ),
    ]
