# Generated by Django 5.1.6 on 2025-03-01 19:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0015_alter_tasksubmission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('testpad_id', models.CharField(max_length=20)),
                ('testpad_checkphrase', models.CharField(max_length=20)),
                ('testpad_link', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('max_points', models.FloatField()),
                ('min_points', models.FloatField()),
                ('attempts_fees', models.BooleanField()),
                ('attempt_fee_amount', models.FloatField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.flow')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.lesson')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testpad_identifier', models.IntegerField()),
                ('is_revised', models.BooleanField()),
                ('points', models.FloatField()),
                ('test_passed', models.BooleanField()),
                ('attempt_number', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.datetime(2025, 3, 1, 19, 52, 7, 368862, tzinfo=datetime.timezone.utc))),
                ('result_at', models.DateField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_attempts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student')),
                ('test_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testassignment')),
            ],
        ),
    ]
