# Generated by Django 5.1.6 on 2025-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='testpad_link',
            field=models.CharField(max_length=200),
        ),
    ]
