# Generated by Django 5.1.6 on 2025-03-02 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_test_testpad_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempts',
            name='testpad_identifier',
        ),
        migrations.AlterField(
            model_name='testattempts',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testattempts',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testattempts',
            name='is_revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testattempts',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testattempts',
            name='result_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempts',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
