# Generated by Django 5.1.6 on 2025-03-02 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_testattempts_testpad_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 0, 37, 20, 694325, tzinfo=datetime.timezone.utc)),
        ),
    ]
