# Generated by Django 5.1.6 on 2025-03-02 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_testattempts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempts',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
