# Generated by Django 5.1.6 on 2025-03-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskattachment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
    ]
