# Generated by Django 5.1.6 on 2025-03-04 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0021_semester_chat_url_alter_tasksubmission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('repository', models.URLField()),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('DECLINED', 'DECLINED')], default='DRAFT', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.projectparticipant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('DECLINED', 'DECLINED')], default='DRAFT', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Проект', max_length=100)),
                ('min_points', models.FloatField(default=0)),
                ('max_points', models.FloatField(default=0)),
                ('bars_statements', models.ManyToManyField(blank=True, related_name='bars_statements', to='education.barsstate')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='education.semester')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.semesterproject'),
        ),
    ]
