# Generated by Django 5.1.5 on 2025-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.URLField(blank=True, null=True)),
                ('is_approved', models.BooleanField()),
            ],
        ),
    ]
